Repository Team-UMC/UMC-Web, pull requests merged in 2024-01, with the labels that each got.

#10 [FEAT] 메인 Header 구현
  package-lock.json
  package.json
  public/index.html
  src/App.css
  src/App.js
  src/assets/header.svg
  src/assets/header/OpenHambuger.svg
  src/assets/header/friend.svg
  src/assets/header/header.svg
  src/assets/header/notification.svg
  src/assets/header/setting.svg
  src/assets/header/smallheader.svg
  src/assets/sidebar/ExitHambuger.svg
  src/layout/header.css
  src/layout/header.jsx
  src/layout/header.style.jsx
  src/pages/main.jsx
Labels: FEAT

#11 [FEAT] 공지사항 글 목록 #6
  package.json
  src/App.js
  src/Data.js
  src/assets/nopin.svg
  src/assets/open-arrow.svg
  src/assets/pin.svg
  src/components/CommonTable.jsx
  src/components/CommonTableColumn.jsx
  src/components/CommonTableRow.jsx
  src/components/NoticeCalendarAdmin.jsx
  src/components/NoticeTitle.jsx
  src/pages/NoticeList.jsx
  src/pages/NoticeMain.jsx
  src/pages/NoticeView.jsx
  yarn.lock
Labels: FEAT

#14 [FEAT] 캘린더 구현
  package-lock.json
  package.json
  src/App.js
  src/components/calendar.css
  src/components/calendar.jsx
Labels: FEAT

#16 [CHORE] ESLint 및 Prettier 설정
  .eslintrc.js
  .prettierignore
  .prettierrc.js
  package-lock.json
  package.json
  src/App.js
  src/app/signup/page.jsx
  src/components/calendar.jsx
  src/index.js
  src/layout/hamburgermenu.jsx
  src/layout/hamburgermenu.style.jsx
  src/layout/header.jsx
  src/layout/header.style.jsx
  src/pages/main.jsx
Labels: CHORE

#17 [FEAT] 공지사항 글작성 페이지 구현
  package-lock.json
  package.json
  src/App.js
  src/assets/campChecked.svg
  src/assets/campUnchecked.svg
  src/assets/file.svg
  src/assets/imgfile.svg
  src/assets/schoolChecked.svg
  src/assets/schoolUnchecked.svg
  src/assets/suggestionChecked.svg
  src/assets/suggestionUnchecked.svg
  src/assets/unionChecked.svg
  src/assets/unionUnchecked.svg
  src/pages/boardwrite.jsx
  src/pages/boardwrite.style.css
Labels: FEAT

#19 [HOTFIX] CommonTable, CommonTableRow, CommonTableColumn 코드 수정
  package.json
  src/App.js
  src/components/CommonTable.jsx
  src/components/CommonTableColumn.jsx
  src/components/CommonTableRow.jsx
  src/pages/NoticeList.jsx
  yarn.lock
Labels: FIX

#21 [DESIGN] 공지사항 게시판 목록 고정핀 이미지 변경
  src/assets/nopin.svg
  src/assets/pin.svg
Labels: DESIGN

#30 [CHORE] 게시판 페이지 및 컴포넌트 파일 분리
  package.json
  src/App.css
  src/App.js
  src/assets/board/pencil-fill.svg
  src/assets/boardCard/branch.svg
  src/assets/boardCard/school.svg
  src/assets/boardCard/union.svg
  src/assets/boardwrite/campChecked.svg
  src/assets/boardwrite/campUnchecked.svg
  src/assets/boardwrite/file.svg
  src/assets/boardwrite/imgfile.svg
  src/assets/boardwrite/schoolChecked.svg
  src/assets/boardwrite/schoolUnchecked.svg
  src/assets/boardwrite/suggestionChecked.svg
  src/assets/boardwrite/suggestionUnchecked.svg
  src/assets/boardwrite/unionChecked.svg
  src/assets/boardwrite/unionUnchecked.svg
  src/assets/oldboard/nopin.svg
  src/assets/oldboard/open-arrow.svg
  src/assets/oldboard/pin.svg
  src/assets/titleIcon/branchIcon.svg
  src/assets/titleIcon/schoolIcon.svg
  src/assets/titleIcon/titledot.svg
  src/assets/titleIcon/unionIcon.svg
  src/components/BoardBox/BoardBox.jsx
  src/components/BoardBox/BoardBoxBranch.jsx
  src/components/BoardBox/BoardBoxSchool.jsx
  src/components/BoardBox/BoardBoxUnion.jsx
  src/components/BoardBox/BoardBoxWrapper.jsx
  src/components/BoardTitle/BoardTitle.jsx
  src/components/BoardTitle/BoardTitleBranch.jsx
  src/components/BoardTitle/BoardTitleSchool.jsx
  src/components/BoardTitle/BoardTitleUnion.jsx
  src/components/NewBoard/BoardTable.jsx
  src/components/NewBoard/BoardWriteButton.jsx
  src/components/OldBoard/CommonTable.jsx
  src/components/OldBoard/CommonTableColumn.jsx
  src/components/OldBoard/CommonTableRow.jsx
  src/components/OldBoard/NoticeCalendarAdmin.jsx
  src/components/OldBoard/NoticeTitle.jsx
  src/components/OldBoard/calendar.css
  src/components/OldBoard/calendar.jsx
  src/components/boardwrite/BoardLabel.jsx
  src/layout/HamburgerMenu/hamburgermenu.jsx
  src/layout/HamburgerMenu/hamburgermenu.style.jsx
  src/layout/Header/header.jsx
  src/layout/Header/header.style.jsx
  src/pages/BoardWrite/boardwrite.jsx
  src/pages/BoardWrite/boardwrite.style.css
  src/pages/NewBoardPage/BoardPage.jsx
  src/pages/OldBoard/NoticeList.jsx
  src/pages/OldBoard/NoticeMain.jsx
  src/pages/OldBoard/NoticeView.jsx
  src/pages/SignUp/signup.jsx
  src/pages/main.jsx
  yarn.lock
Labels: CHORE

#33 [FEAT] Header 및 HamburgerMenu, Calendar 수정
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/assets/header/setting.svg
  src/assets/main/LeftArrow.svg
  src/assets/main/LeftArrowBlack.svg
  src/assets/main/LeftArrowGray.svg
  src/assets/main/RightArrow.svg
  src/assets/main/RightArrowBlack.svg
  src/assets/main/RightArrowGray.svg
  src/components/Header/HamburgerMenu.jsx
  src/components/Header/LeftContainer.jsx
  src/components/Header/RightContainer.jsx
  src/components/Main/Calendar/CalendarData.js
  src/components/Main/Calendar/RowContents.jsx
  src/components/Main/Calendar/calendar.css
  src/components/Main/Calendar/calendar.jsx
  src/components/Main/MainDescription.jsx
  src/components/Main/Notification/Notification.jsx
  src/components/Main/Notification/NotificationData.js
  src/components/Main/TodayILearned/TodayILearned.jsx
  src/components/Main/TodoList/TodoList.jsx
  src/components/signup/WriteInput.jsx
  src/features/.gitkeep
  src/layout/HamburgerMenu/hamburgermenu.jsx
  src/layout/HamburgerMenu/hamburgermenu.style.jsx
  src/layout/Header/MenuItem.js
  src/layout/Header/header.jsx
  src/layout/Header/header.style.jsx
  src/pages/SignUp/signup.style.jsx
  src/pages/boardwrite.jsx
  src/pages/main.jsx
  src/styles/.gitkeep
  src/types/.gitkeep
  src/utils/.gitkeep
  yarn.lock
Labels: FEAT

#39 [FEAT] 운영진 관리 페이지 캘린더 부분 구현
  package-lock.json
  src/App.js
  src/assets/management/calenderChecked.svg
  src/assets/management/calenderUnchecked.svg
  src/assets/management/challengerChecked.svg
  src/assets/management/challengerUnchecked.svg
  src/assets/management/management.svg
  src/assets/management/setnoticeChecked.svg
  src/assets/management/setnoticeUnchecked.svg
  src/assets/mywrite/mywriteCampChecked.svg
  src/assets/mywrite/mywriteCampUnchecked.svg
  src/assets/mywrite/mywriteSchoolChecked.svg
  src/assets/mywrite/mywriteSchoolUnchecked.svg
  src/assets/mywrite/mywriteSuggestionChecked.svg
  src/assets/mywrite/mywriteSuggestionUnchecked.svg
  src/assets/mywrite/mywriteUnionChecked.svg
  src/assets/mywrite/mywriteUnionUnchecked.svg
  src/assets/mywrite/reset.svg
  src/assets/search.svg
  src/components/Management/Button.jsx
  src/components/Management/ChallengerType.jsx
  src/components/Management/Classify.jsx
  src/components/Management/ManagementComponent.jsx
  src/components/Management/ManagementType.jsx
  src/components/Management/SearchChallenger.jsx
  src/components/Management/SelectLocal.jsx
  src/components/Management/StartendDate.jsx
  src/components/Management/StartendTime.jsx
  src/components/Management/Title.jsx
  src/components/MyWriting/BoardType.jsx
  src/components/MyWriting/CommentList.jsx
  src/components/MyWriting/GreatList.jsx
  src/components/MyWriting/MyWritingList.jsx
  src/components/MyWriting/Title.jsx
  src/components/MyWriting/Type.jsx
  src/components/MyWriting/TypeComponent.jsx
  src/components/boardwrite/BoardCamp.jsx
  src/components/boardwrite/BoardLabel.jsx
  src/components/boardwrite/BoardSchool.jsx
  src/components/boardwrite/BoardText.jsx
  src/components/boardwrite/BoardTitle.jsx
  src/components/boardwrite/BoardUnion.jsx
  src/pages/BoardWrite/boardwrite.jsx
  src/pages/BoardWrite/boardwrite.style.css
  src/pages/Management/management.jsx
  src/pages/MyWrite/MyWrite.jsx
  yarn.lock
Labels: FEAT

#41 [FEAT] 운영자 관리 페이지 구현
  src/Data.js
  src/assets/admin/AdminTitle.svg
  src/assets/admin/checked.svg
  src/assets/board/list/Pinned.svg
  src/components/Admin/AdminCompletionButton.jsx
  src/components/Admin/AdminTable.jsx
  src/components/Admin/AdminTitle.jsx
  src/components/NewBoard/BoardTable.jsx
  src/layout/Admin/AdminPage.jsx
  src/pages/NewBoardPage/BoardPage.jsx
  src/pages/NewBoardPage/BoardPageRoute.jsx
Labels: FEAT

#47 [FIX] 게시판 페이지 수정
  src/App.js
  src/components/BoardBox/BoardBoxBranch.jsx
  src/components/BoardBox/BoardBoxSchool.jsx
  src/components/BoardBox/BoardBoxUnion.jsx
  src/components/BoardBox/BoardBoxWrapper.jsx
  src/components/BoardTitle/BoardTitleBranch.jsx
  src/components/BoardTitle/BoardTitleSchool.jsx
  src/components/BoardTitle/BoardTitleUnion.jsx
  src/layout/Admin/AdminPage.jsx
  src/pages/NewBoardPage/BoardPage.jsx
  src/pages/NewBoardPage/BoardPageRoute.jsx
Labels: FIX
