Repository Team-UMC/UMC-Web, pull requests merged in 2024-02, with the labels that each got.

#69 [CHORE] 코드 주석 추가
  src/App.js
  src/components/Board/BoardSearch.jsx
  src/components/Board/BoardTable.jsx
  src/components/Board/BoardWriteButton.jsx
  src/components/BoardBox/BoardBox.jsx
  src/components/BoardTitle/BoardTitle.jsx
  src/components/Gallery/GalleryDetail/GalleryDetailProfile.jsx
  src/components/Gallery/GalleryDetail/GalleryListButton.jsx
  src/components/Gallery/GalleryList.jsx
  src/components/Gallery/GallerySearchBar.jsx
  src/components/Gallery/GallerySwitch.jsx
  src/components/Gallery/GalleryTitle.jsx
  src/components/Gallery/GalleryWriteButton.jsx
  src/components/Management/NoticePin/AdminCompletionButton.jsx
  src/components/Management/NoticePin/AdminTitle.jsx
  src/components/Management/NoticePin/NewAdminTable.jsx
  src/components/Management/NoticePin/PinnedTable.jsx
  src/layout/Header/Header.jsx
  src/layout/NoticePin/AdminPage.jsx
  src/pages/BoardPage/BoardPage.jsx
  src/pages/BoardPage/BoardPageRoute.jsx
  src/pages/Gallery/GalleryDetailPage.jsx
  src/pages/Gallery/GalleryPage.jsx
Labels: CHORE

#71 [FEAT] TDL 페이지 구현
  package-lock.json
  package.json
  src/App.js
  src/assets/todayilearn/calender.svg
  src/assets/todayilearn/detail.svg
  src/assets/todayilearn/figma.svg
  src/assets/todayilearn/file.svg
  src/assets/todayilearn/fiximg.svg
  src/assets/todayilearn/modalimg.svg
  src/assets/todayilearn/notion.svg
  src/assets/todayilearn/removeimg.svg
  src/assets/todolist/aftertime.svg
  src/assets/todolist/aftertimechecked.svg
  src/assets/todolist/clock.svg
  src/assets/todolist/complete.svg
  src/assets/todolist/daytime.svg
  src/assets/todolist/imgchoose.svg
  src/assets/todolist/listcheckedimg.svg
  src/assets/todolist/listuncheckedimg.svg
  src/assets/todolist/plant.svg
  src/assets/todolist/uncomplete.svg
  src/components/DateSelectCalendar.jsx
  src/components/Management/ManagementComponent.jsx
  src/components/ToDoList/AddTDL.jsx
  src/components/ToDoList/ComponentTDL.jsx
  src/components/ToDoList/TitleTDL.jsx
  src/components/TodayILearn/AddTIL.jsx
  src/components/TodayILearn/Calender.jsx
  src/components/TodayILearn/ComponentTIL.jsx
  src/components/TodayILearn/DetailComponent.jsx
  src/components/TodayILearn/DetailTIL.jsx
  src/components/TodayILearn/ListTIL.jsx
  src/components/TodayILearn/NewTIL.jsx
  src/components/TodayILearn/OptionTIL.jsx
  src/components/TodayILearn/modalTIL.jsx
  src/components/boardwrite/BoardTitle.jsx
  src/layout/Header/Header.jsx
  src/pages/Management/NoticePin/AdminManagePage.jsx
  src/pages/ToDoList/TodoList.jsx
  src/pages/TodayILearn/TodayILearn.jsx
  yarn.lock
Labels: FEAT

#74 [FEAT] 설정 페이지 구현
  package.json
  src/App.js
  src/assets/Setting/close-circle.svg
  src/assets/Setting/paper-plane.svg
  src/assets/Setting/question.svg
  src/components/Management/NoticePin/AdminTitle.jsx
  src/components/Setting/Setting.style.jsx
  src/components/Setting/SettingContents.jsx
  src/components/Setting/SettingMenu.jsx
  src/components/Setting/SettingTitle.jsx
  src/pages/Setting/SettingPage.jsx
  yarn.lock
Labels: FEAT

#75 [CHORE] 운영진 관리 페이지 수정
  package-lock.json
  package.json
  src/App.js
  src/assets/management/challengeradd.svg
  src/assets/management/challengerremove.svg
  src/assets/management/searchimg.svg
  src/assets/management/setnoticeChecked.svg
  src/assets/todayilearn/DetailLine.svg
  src/components/Management/ChallengerPosition.jsx
  src/components/Management/ChallengerType.jsx
  src/components/Management/Classify.jsx
  src/components/Management/ManagementComponent.jsx
  src/components/Management/ManagementType.jsx
  src/components/Management/SearchChallenger.jsx
  src/components/Management/SelectLocal.jsx
  src/components/Management/StartendDate.jsx
  src/components/Management/Title.jsx
  src/components/MyWriting/BoardType.jsx
  src/components/MyWriting/MyWritingList.jsx
  src/components/MyWriting/Title.jsx
  src/components/ToDoList/AddTDL.jsx
  src/components/ToDoList/ComponentTDL.jsx
  src/components/TodayILearn/ButtonTIL.jsx
  src/components/TodayILearn/Calender.jsx
  src/components/TodayILearn/ComponentTIL.jsx
  src/components/TodayILearn/DetailComponent.jsx
  src/pages/Management/Management.jsx
  src/pages/Management/NoticePin/AdminManagePage.jsx
  src/pages/MyWrite/MyWrite.jsx
  yarn.lock
Labels: CHORE

#77 [DESIGN] 메인 페이지 캘린더 스타일링
  src/apis/app/auth/KakaoAuth.jsx
  src/apis/app/auth/NaverAuth.jsx
  src/apis/setting.js
  src/assets/main/calendar.svg
  src/components/Main/Calendar/CalendarData.js
  src/components/Main/Calendar/calendar.css
  src/components/Main/Calendar/calendar.jsx
  yarn.lock
Labels: DESIGN

#84 [DESIGN] DateSelectCalendar 컴포넌트 스타일링
  src/components/DateSelectCalendar.jsx
  src/components/Main/Calendar/calendar.jsx
  src/components/dateselectcalendar.css
Labels: DESIGN

#86 [FIX] 메인 페이지 캘린더 수정
  package.json
  src/App.js
  src/components/Main/Calendar/calendar.css
  src/components/Main/Calendar/calendar.jsx
  src/components/Management/ManagementComponent.jsx
  src/components/TodayILearn/Calender.jsx
  src/components/TodayILearn/ComponentTIL.jsx
  src/pages/MyWrite/MyWrite.jsx
  yarn.lock
Labels: FIX

#89 [FIX] 설정 내용 컴포넌트(SettingContents) 분리
  src/components/Setting/SettingContents.jsx
  src/components/Setting/SettingContents/CustomSetting.jsx
  src/components/Setting/SettingContents/CustomerServiceSetting.jsx
  src/components/Setting/SettingContents/EtcSetting.jsx
  src/components/Setting/SettingContents/UmcInfoSetting.jsx
  src/components/Setting/SettingContents/WebInfoSetting.jsx
Labels: FIX
